config/routes.rb
Rails.application.routes.draw do
  mathjax 'mathjax'
  get 'home/index'
  default_url_options host: 'ruby.cjtsai.com'
  default_url_options protocol: :https
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  #get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  #get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  #get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  #post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  #patch "/blog_posts/:id", to: "blog_posts#update"
  #delete "/blog_posts/:id", to: "blog_posts#destroy"
  resources :problems, only: [:index]

  resources :user_problems, only: [:create, :update] do
    member do
      post :advance
    end
  end

  resources :blog_posts do
    resources :comments
  end

  resources :users, only: [] do
    resources :blog_posts, only: [:index]
  end
  root 'blog_posts#index', defaults: { user_id: 44 }

end

app/models/problem.rb
# app/models/problem.rb
class Problem < ApplicationRecord
    validates :name, presence: true
    validates :url, presence: true, format: { with: URI::regexp(%w[http https]), message: "must be a valid URL" }
    validates :category, presence: true
    has_many :user_problems
    has_many :users, through: :user_problems
end
  

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
    def index
      @problems = Problem.all
    end
  end
  

app/views/problems/_problem.html.erb
<!-- app/views/problems/_problem.html.erb -->
<turbo-frame id="problem_<%= problem.id %>">
    <div class="problem-item" data-problem-id="<%= problem.id %>">
      <h3><%= problem.name %></h3>
      <p>Status: <%= user_problem.status.present? ? user_problem.status.humanize : "Not Started" %></p>
      <%= button_to "Advance Status", advance_user_problem_path(user_problem),
      method: :post,
      data: {turbo: false},
      remote: true,
      class: "advance-status-btn" %>
    </div>
  </turbo-frame>
  

app/views/problems/index.html.erb
<!-- app/views/problems/index.html.erb -->
<h1>Your Problem Checklist</h1>

<% @problems.each do |problem| %>
  <% user_problem = current_user.user_problems.find_or_create_by(problem: problem) %>
  <%= render partial: "problems/problem", locals: { problem: problem, user_problem: user_problem } %>
<% end %>